// flow-typed signature: 8a23fc9801cbabe856b36850e0a6895f
// flow-typed version: <<STUB>>/nearley_v^2.8.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nearley'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nearley' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nearley/bin/nearley-railroad' {
  declare module.exports: any;
}

declare module 'nearley/bin/nearley-test' {
  declare module.exports: any;
}

declare module 'nearley/bin/nearley-unparse' {
  declare module.exports: any;
}

declare module 'nearley/bin/nearleyc' {
  declare module.exports: any;
}

declare module 'nearley/examples/calculator/calculator' {
  declare module.exports: any;
}

declare module 'nearley/examples/calculator/grammar' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/AycockHorspool' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/csscolor' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/csv' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/JoopLeo' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/left' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/lua' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/numberstring' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/right' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/tosh' {
  declare module.exports: any;
}

declare module 'nearley/examples/js/wikipedia' {
  declare module.exports: any;
}

declare module 'nearley/examples/old-language-specification' {
  declare module.exports: any;
}

declare module 'nearley/examples/railroad-experimental/custom-canvas' {
  declare module.exports: any;
}

declare module 'nearley/examples/token' {
  declare module.exports: any;
}

declare module 'nearley/lib/compile' {
  declare module.exports: any;
}

declare module 'nearley/lib/generate' {
  declare module.exports: any;
}

declare module 'nearley/lib/lint' {
  declare module.exports: any;
}

declare module 'nearley/lib/nearley-language-bootstrapped' {
  declare module.exports: any;
}

declare module 'nearley/lib/nearley' {
  declare module.exports: any;
}

declare module 'nearley/lib/stream' {
  declare module.exports: any;
}

declare module 'nearley/test/_shared' {
  declare module.exports: any;
}

declare module 'nearley/test/benchmark' {
  declare module.exports: any;
}

declare module 'nearley/test/ebnf' {
  declare module.exports: any;
}

declare module 'nearley/test/launch' {
  declare module.exports: any;
}

declare module 'nearley/test/negatable' {
  declare module.exports: any;
}

declare module 'nearley/test/profile' {
  declare module.exports: any;
}

declare module 'nearley/www/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nearley/bin/nearley-railroad.js' {
  declare module.exports: $Exports<'nearley/bin/nearley-railroad'>;
}
declare module 'nearley/bin/nearley-test.js' {
  declare module.exports: $Exports<'nearley/bin/nearley-test'>;
}
declare module 'nearley/bin/nearley-unparse.js' {
  declare module.exports: $Exports<'nearley/bin/nearley-unparse'>;
}
declare module 'nearley/bin/nearleyc.js' {
  declare module.exports: $Exports<'nearley/bin/nearleyc'>;
}
declare module 'nearley/examples/calculator/calculator.js' {
  declare module.exports: $Exports<'nearley/examples/calculator/calculator'>;
}
declare module 'nearley/examples/calculator/grammar.js' {
  declare module.exports: $Exports<'nearley/examples/calculator/grammar'>;
}
declare module 'nearley/examples/js/AycockHorspool.js' {
  declare module.exports: $Exports<'nearley/examples/js/AycockHorspool'>;
}
declare module 'nearley/examples/js/csscolor.js' {
  declare module.exports: $Exports<'nearley/examples/js/csscolor'>;
}
declare module 'nearley/examples/js/csv.js' {
  declare module.exports: $Exports<'nearley/examples/js/csv'>;
}
declare module 'nearley/examples/js/JoopLeo.js' {
  declare module.exports: $Exports<'nearley/examples/js/JoopLeo'>;
}
declare module 'nearley/examples/js/left.js' {
  declare module.exports: $Exports<'nearley/examples/js/left'>;
}
declare module 'nearley/examples/js/lua.js' {
  declare module.exports: $Exports<'nearley/examples/js/lua'>;
}
declare module 'nearley/examples/js/numberstring.js' {
  declare module.exports: $Exports<'nearley/examples/js/numberstring'>;
}
declare module 'nearley/examples/js/right.js' {
  declare module.exports: $Exports<'nearley/examples/js/right'>;
}
declare module 'nearley/examples/js/tosh.js' {
  declare module.exports: $Exports<'nearley/examples/js/tosh'>;
}
declare module 'nearley/examples/js/wikipedia.js' {
  declare module.exports: $Exports<'nearley/examples/js/wikipedia'>;
}
declare module 'nearley/examples/old-language-specification.js' {
  declare module.exports: $Exports<'nearley/examples/old-language-specification'>;
}
declare module 'nearley/examples/railroad-experimental/custom-canvas.js' {
  declare module.exports: $Exports<'nearley/examples/railroad-experimental/custom-canvas'>;
}
declare module 'nearley/examples/token.js' {
  declare module.exports: $Exports<'nearley/examples/token'>;
}
declare module 'nearley/lib/compile.js' {
  declare module.exports: $Exports<'nearley/lib/compile'>;
}
declare module 'nearley/lib/generate.js' {
  declare module.exports: $Exports<'nearley/lib/generate'>;
}
declare module 'nearley/lib/lint.js' {
  declare module.exports: $Exports<'nearley/lib/lint'>;
}
declare module 'nearley/lib/nearley-language-bootstrapped.js' {
  declare module.exports: $Exports<'nearley/lib/nearley-language-bootstrapped'>;
}
declare module 'nearley/lib/nearley.js' {
  declare module.exports: $Exports<'nearley/lib/nearley'>;
}
declare module 'nearley/lib/stream.js' {
  declare module.exports: $Exports<'nearley/lib/stream'>;
}
declare module 'nearley/test/_shared.js' {
  declare module.exports: $Exports<'nearley/test/_shared'>;
}
declare module 'nearley/test/benchmark.js' {
  declare module.exports: $Exports<'nearley/test/benchmark'>;
}
declare module 'nearley/test/ebnf.js' {
  declare module.exports: $Exports<'nearley/test/ebnf'>;
}
declare module 'nearley/test/launch.js' {
  declare module.exports: $Exports<'nearley/test/launch'>;
}
declare module 'nearley/test/negatable.js' {
  declare module.exports: $Exports<'nearley/test/negatable'>;
}
declare module 'nearley/test/profile.js' {
  declare module.exports: $Exports<'nearley/test/profile'>;
}
declare module 'nearley/www/main.js' {
  declare module.exports: $Exports<'nearley/www/main'>;
}
